public class Main {
    public static void main(String[] args) {
        Human Mother = new Human("Мама");
        Human Father = new Human("Папа");
        Human Baby = new Human("Малыш");
        Human Who = new Human("Кто");
        Human All = new Human("Все");
        Human Bosse = new Human("Боссе");
        Human Betan = new Human("Бетан");
        Place Table = new Place("Стол");
        Place Lunch = new Place("Обед");
        Place Fish = new Place("Вареная Треска");
        Place Soup = new Place("Овощной Суп");
        Place Cutlets = new Place("Селедочные Котлеты");
        Place Chops = new Place("Телячьи Отбивные");
        Place Dessert = new Place("Сладкое");
        Place Strawberry = new Place("Клубника");
        Place Holidays = new Place("Летние Каникулы");
        Place House = new Place("Дом");
        Place YachtClub = new Place("Яхтклуб");
        Place Sport = new Place("Парусный Спорт");
        Place Farm = new Place("Крестьянский Хутор");
        Place There = new Place("Там");
        Place Horses = new Place("Лошади");
        Place This = new Place("Это");
        Place FarewellDinner = new Place("Прощальный Обед");
        Place Feast = new Place("Маленький Пир");
        Mother.Action(Mother, Action.Understand);
        Who.Action(Who, Action.MessUp);
        Mother.ActionWithListening(Father, Action.Tell);
        Father.ActionWithoutTalking(Action.Come);
        Father.ActionWithoutTalking(Action.Lunch);
        Mother.Action(Mother, Action.Repeat);
        Mother.Phrase("\"Во время еды надо, чтобы было весело\" ");
        Baby.Action(Baby, Action.Think);
        All.Action(All, Action.Fun);
        All.ContactWithPlace(All, Action.Sit, Condition.Behind, Table);
        All.ActionWithoutTalking(Action.Talk);
        Baby.Action(Baby, Action.Speak);
        Baby.ActionWithoutTalking(Action.Eat);
        Lunch.PlaceCondition(Lunch, Condition.On);
        Fish.JustPlace(Fish);
        Soup.JustPlace(Soup);
        Cutlets.JustPlace(Cutlets);
        Mother.Action(Mother, Action.Give);
        All.ContactWithPlaceWithoutAction(All, Chops);
        Mother.ContactWithPlaceWithoutActionAndTalking(Condition.On, Dessert);
        Mother.ContactWithPlaceWithoutPr(Mother, Action.Give, Strawberry);
        Holidays.PlaceCondition(Holidays, Condition.Start);
        Bosse.ActionWithTwoPeople(Bosse, Betan, Action.Leave);
        House.PlaceCondition(House, Condition.From);
        Bosse.ContactWithPlace(Bosse, Action.Leave, Condition.In,YachtClub);
        Bosse.ContactWithPlaceWithoutConditionAndTalking(Action.Study, Sport);
        Bosse.ContactWithPlace(Bosse, Action.Leave, Condition.In, Farm);
        Horses.PlaceConditionTwoPlaces(There, Horses, Condition.Is);
        This.PlaceConditionTwoPlaces(This, FarewellDinner, Condition.Was);
        Mother.Action(Mother, Action.TryHard);
        FarewellDinner.PlaceCondition(FarewellDinner, Condition.TurnedInto);
        Feast.PlaceCondition(Feast, Condition.In);
    }
}